<?xml version="1.0"?>
<package format="3">
  <name>amr_warehouse_sim</name>
  <version>0.0.1</version>
  <description>AMR warehouse simulation with Gazebo, Lidar, TF, and SLAM Toolbox</description>
  <maintainer email="ina@example.com">ina</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>ament_index_python</depend>
  <depend>rclpy</depend>
  <depend>action_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>nav2_msgs</depend>
  <depend>lifecycle_msgs</depend>
  <depend>launch</depend>
  <depend>launch_ros</depend>
  <depend>rosgraph_msgs</depend>
  <depend>tf2_ros</depend>

  <depend>ros_gz_sim</depend>
  <depend>ros_gz_bridge</depend>
  <depend>robot_state_publisher</depend>
  <depend>rviz2</depend>

  <depend>laser_filters</depend>
  <depend>nav2_bringup</depend>
  <depend>slam_toolbox</depend>

  <test_depend>pytest</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
